name: lifelong_learning_cards
description: A Flutter application for lifelong learners to manage and review knowledge cards.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  provider: ^6.0.0
  
  # 本地存储
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  
  # Markdown 支持
  flutter_markdown: ^0.6.17
  markdown: ^7.1.0
  
  # UI 组件
  flutter_slidable: ^3.0.0
  animations: ^2.0.0
  
  # 工具类
  intl: ^0.18.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
