name: lifelong_learning_cards
description: A Flutter application for lifelong learners to manage and review knowledge cards.


flutter:
  uses-material-design: true    


  assets:
    - assets/icons/
  # Add your fonts configuration here
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: fonts/NotoSansSC-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansSC-Medium.ttf
          weight: 500
        - asset: fonts/NotoSansSC-Bold.ttf
          weight: 700

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  pasteboard: ^0.4.0  # 用于处理剪贴板图片数据
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7  # 添加SVG支持
  
  # 状态管理
  provider: ^6.0.0
  
  # 本地存储
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.8.0
  shared_preferences: ^2.2.0
  
  # Markdown 支持
  flutter_markdown: ^0.6.17
  google_fonts: ^6.1.0
  markdown: ^7.1.0
  
  # UI 组件
  flutter_slidable: ^3.0.0
  animations: ^2.0.0
  
  # 工具类
  intl: ^0.18.0
  uuid: ^4.0.0
  file_picker: ^5.3.1
  image_picker: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


